type Dir = "e" | "w" | "se" | "sw" | "ne" | "nw";

export function doIt() {
  const parsed = input.split(`\n`).map((line) => {
    const dirs: Dir[] = [];
    let pos = { x: 0, y: 0 };
    while (line.length) {
      switch (line[0]) {
        case "e":
        case "w":
          dirs.push(line[0]);
          line = line.slice(1);
          break;
        default:
          dirs.push(line.slice(0, 2) as Dir);
          line = line.slice(2);
          break;
      }
    }
    dirs.forEach((d) => {
      switch (d) {
        case "e":
          pos.x += 1;
          break;
        case "w":
          pos.x -= 1;
          break;
        case "se":
          pos.x += 0.5;
          pos.y += 1;
          break;
        case "sw":
          pos.x -= 0.5;
          pos.y += 1;
          break;
        case "ne":
          pos.x += 0.5;
          pos.y -= 1;
          break;
        case "nw":
          pos.x -= 0.5;
          pos.y -= 1;
          break;
      }
    });
    return pos;
  });
  let tilted = parsed.map(serialize).reduce((set, pos) => {
    set.has(pos) ? set.delete(pos) : set.add(pos);
    return set;
  }, new Set<string>());
  const first = tilted.size;

  let step = 0;
  while (step++ < 100) {
    tilted = next(tilted);
  }
  const second = tilted.size;
  console.log(first, second);
}

function getNeighbours(p: { x: number; y: number }) {
  return [
    [1, 0],
    [-1, 0],
    [0.5, 1],
    [-0.5, 1],
    [0.5, -1],
    [-0.5, -1],
  ].map(([dx, dy]) => ({ x: p.x + dx, y: p.y + dy }));
}

function serialize(pos: { x: number; y: number }) {
  return `${pos.x};${pos.y}`;
}

function deserialize(pos: string) {
  const [x, y] = pos.split(";").map((c) => +c);
  return { x, y };
}

function next(state: Set<string>) {
  const candidates = Array.from(state)
    .map(deserialize)
    .map((pos) => [pos, ...getNeighbours(pos)])
    .reduce((a, b) => [...a, ...b])
    .map(serialize)
    .reduce((set, pos) => set.add(pos), new Set<string>());
  candidates.forEach((candidate) => {
    const pos = deserialize(candidate);
    const blackNeighbours = getNeighbours(pos).filter((n) =>
      state.has(serialize(n))
    ).length;
    const shouldBeBlack =
      blackNeighbours === 2 || (state.has(candidate) && blackNeighbours === 1);
    if (!shouldBeBlack) candidates.delete(candidate);
  });

  return candidates;
}
/*
const input = `sesenwnenenewseeswwswswwnenewsewsw
neeenesenwnwwswnenewnwwsewnenwseswesw
seswneswswsenwwnwse
nwnwneseeswswnenewneswwnewseswneseene
swweswneswnenwsewnwneneseenw
eesenwseswswnenwswnwnwsewwnwsene
sewnenenenesenwsewnenwwwse
wenwwweseeeweswwwnwwe
wsweesenenewnwwnwsenewsenwwsesesenwne
neeswseenwwswnwswswnw
nenwswwsewswnenenewsenwsenwnesesenew
enewnwewneswsewnwswenweswnenwsenwsw
sweneswneswneneenwnewenewwneswswnese
swwesenesewenwneswnwwneseswwne
enesenwswwswneneswsenwnewswseenwsese
wnwnesenesenenwwnenwsewesewsesesew
nenewswnwewswnenesenwnesewesw
eneswnwswnwsenenwnwnwwseeswneewsenese
neswnwewnwnwseenwseesewsenwsweewe
wseweeenwnesenwwwswnew`;
/** */

const input = `eweneeewwneeeneneseweeeee
eenweesewseweene
nenwnenenenenenenwewnwwwnenwnwnwese
seseseeneseseseswneeswseseseseseseesese
nwsewewwwwewwwwwnwnwwwnwwsww
weseeewwnwwwswnwswnwewneswnwnwswsw
eeeweneeeeneeeee
eneswswneswwsenwwsenweswnwswswswsesw
nwseeeeewneswswsesenweeenweeee
swswnwnwseswneseswswnwsenenwsenwswwese
nwswsenesewnwwnwnewnenwwwwwnwwse
swwsesesesenwseswswswswseseseseeeswnwse
neneneeneenenenwnenenenwseswnenee
swnenwnenenwnenwewwswnweenwnwnwnwnese
swsewseseswseeswswseswsese
wnewnweneenenenwsenenenesweswwneswnw
nwenenwnenwnwnwnwswnenw
esesesesesesesesesesesesesesesenwsese
nenwnwnwnwenwnenwnwnwnwsenenwnwswnenwse
eewnenesenwneswenewneneneeeewne
ewwneseeeeneneeneneneneenenenenene
eweseseeneneneeswnwwnenewneneenee
sesweswnenwwnwsewnwnwnweewseeswwe
seeeseneeweeseee
swseneneewwnenwwwwnwsesese
neenweeseneswseseswwwnweneeweese
eeeseswseseeeeeeeeneeeenwese
wnenenenewneeneneenenenesenene
nwnwnewwsesenenwnwwwewwwwwwnw
wneswswwswswswwswswswwseswsww
nenenesenwneswwwnwnwnwswswwnwenewse
neenenenenenenenenwswnenwnwsenenenenewnene
wwswwsewnenewsewwwwwwwnwswse
wwwwwwwwwewewwwwwwwsw
nwneweseeseeneseeeneesewewwe
swwenwnenwnwewwseeesenwswnwwwsw
wwswwwsewweswswwneneewswwswwsww
swnwswenwseswswswswswnwswseswswswswsese
eeeneeneswnenwneenenesee
enwnwnenwnesenwnwwenwnwswswnwwe
nwnenenenenwnwnwswswseneneneswnwnwswnene
seseeenweweenenwneeneneeeeseene
nenwnenenenwneeenenwnewswnenw
wswneewswswneneswsewswseneseswswseswsw
wewenesweeeeeneneweneneeenese
senwnwnenwenwnwwnenwsesenwnwnwnwnwsenw
seneeneeswseneenwenwnwswneeneenwe
senenwsenesewswwseseswseneseswswnenwswe
wwswewwenweewwwwwswneswww
swwnwnwneneneneeneneneneenwswnenenww
nwwnwwsenwnwnwswnwwwsenwwnewwww
nwswswnwenwseeeewsenwseenese
eweeseeeswenwnweswenwnewwsew
neeswenweseeeeeeseeeee
nesenwenenwnesenwwneneneneneneneswnene
swswswswswswseswswneswwswneneswswsewsw
eeeenweesweeeseeeeee
nwenesenwneswnewsenenwwnwsewswwnewse
seeeseseenwseeswwseseswwenesesese
wewnwnwwwwwwenwwwwwwwwww
enwswswswnwnwneeeewseeseeeseseese
newenwnenwewswnenwnwnwnwnwnwnenenwnenw
wwnwnwnwswnwnwwwnwnwsenwnwewnwnwww
nwnwswnwnwwwwwwwnwwwnwnewsewww
swsenweeeseseseweneeeseseswseseenw
sesenwseeneseseweseseseseesewnweese
seeneweesewseneeeseseeseseesee
swswswswswswswswnwsweswswswswswseswswsw
nwseeeseseseesweeeseenwsweseseeee
seseseneseseseseseseswnesesesesewsenww
wwnewwnwwsewnwewwnw
wwwnwwwwswwswwwswsesenw
nwnwwwsenwwnwnwnwnwnwnwnwnwwswnwnwe
newnenwnenenenwseneneswnenwnenene
esweeeneswneneweneseneewwenese
sesewnwseseswsesenewseneseeneswsenwe
seeeeeeeeeenenenweneeesweene
seeswenwseeswswweeenweneneseenene
nenwnenenwnenenwnwnenwnwnenwnenenwsw
nesenewswsewnwswwswweswswswwswnwewse
nwsweswswswwenewwswswwswwswnewsww
sewseseswswseseseeseseswseswswesewsw
nenenenenenwnwsenwnenenewnwsenwnenwnenw
sewwwsewnewweswsenenwwwswenwnenww
eewwswwwwwswwwe
nwsenwswwnwseenwnwnwnwnwnenwnwwnwww
nenwnwnenwnwnenenwnwwseneenwnwnwne
neneswswsweswsewswnesewneswwswnenewnw
wnwewnwwwwwwwwwneswnwnwnwwwse
eswswswswswswswswswswseswnwswswnwswsesw
nenenwnenwnenwnenwnwnenenenenenwnwsenenwse
nwnwnwnwnesenenwswnwnwnenwnwnenwnwnwnwnenw
swswwwwswwwwweswsww
enewswwwswwwwswsewwwwwwwswsw
wsesesesesesesesewneweswewseswseese
neeneneneneenenenweeneneneeeeesw
swneneenenenwswewnweneeneneneneneenwsw
wwwnwwnwwwnwweweewnwwwwsw
nwwsewwnwwwnwnwewwwnwnenwwww
enwnenwnenwnenewnwewne
nwewseneswneeewnwswenwswsenwswwne
wwswnewswswwwswwnwwswseesww
swnwnwenwnwnenwswneenwne
newnwswwswswswswswwseswseswneswswswsw
wswseeswswneswswwswwsweewwwswe
neeeeseenwswewweeneneenenenenee
wswwewneswswwwwwwnwwwsenwwww
swswneswsewewseneesweenwnwseneee
swswnwswswwwsewswwwwwwwwww
wnwsesesesesesesesesenese
nwseeeseneeswsenenweseseeswsesewe
esesewewnwseseeeseseeseesee
neswnweseswswswnwswswswswnwwneseeswnw
enwnwnwwseenenwnwsenwnwwswnwwwnwne
swseswseneswneswwnwweswnwwnwseswswse
nwneneenenwswnwsewsenwswnwnwnesw
swneswseseseswswseseseswseswsesesesenewse
swesweeswswswsenwswswnwnwswseswswswsw
senenwswnwseseseeseswseenwnwwnwenwe
enweneneneswneeneneneneeneneeene
sweswseeeeeeeseeesenwnwnwse
neneneneeneneneeneneneenewneneneneswne
wnesewnwneswwsenwnesenwwswnwenesenww
neenewsweweeeeeseeeeeesee
nwnwnenwnenwswneewnenenwnenenenwnwsewene
eseweseseeeeeeseseeeeeneese
swswswswenwwswswswsweswswswswswswnenw
wsenenewnenenenenenesenenenenenenenwne
enewnwneswnenesewnesenwne
wnwwwenwnwnwnwnwnwwnw
eeseseswswwnweneweneeeneeeswe
nwnesewswswswwwsww
eeewnweeeeeeeeneneesesweee
wnweswnwnwnwneseswnwnwnwnw
nenenenwnenenwnenesenenwsw
nwswnewwswsewneswnesewwwwsewswnw
eneseeneswneneneeeeenwneeneeene
nenenwenenwneenenenwnwnewnwneswnenenwne
wseswseswenwneeneseeeseseseesewsenese
wnwnwwwwnwswnwenwnwswwwnwwewwww
neneeeneneneseeneneneneeeneneeswnenw
neneneeeneswneneneeneenenenenesenenew
nwwwwnwnwnwnwwnwswnwnwnwwenwnwnww
wsewwwwwwnwwwwewwnenwswwwww
nwneneesenenenwswnwnewswnenenenenwnenenw
seseswsesesenewwnwseswseswneeswnesee
eswneneneswnwnenenwsenwnwnenenwnwnenwnwnenw
seneesenenweeswwneeneswneswneseenwnw
wwwnwnwewnwnwnwnwnwnwnwewnwnwnwnwnw
enenewneneneneseneewnwneeewenese
enenenenenenenwneneeseneneenenenewswne
esesenwseseseseseseseseseswsenwsesesese
nwnwwwnwnwwwnwsewneseseswnwnwnwsewne
eswnwweeswnenweneseee
nwnenwnwsenwnwnwnwsewnwnwnwnwnenwnenenw
eneeneswnenenesenenenenenw
sesewweseseseeeseseewseneseseee
swesenwnwwneeenenwswsweswswwnwnwnww
nwnwnwnenwnenenenwwnwnwnenwnwnwnwsenwswnwnw
seseseswseswseswswseseswnwseeswswswsenw
swseswseswswwswseeneseswseseseseseswsesw
sesewseesewneswneesesesenw
sesenesweseseseseswwseseswswnwsenesewsw
nenenwsenwnwwnwwnwnenwnwnwnwnwnwenwnw
swneswswwswwwswswswseswswswswswwwsw
seneseseeweeeseeweeseweneese
sesenwseseseneseseseesesenwneswswnwnwse
swseswwswseswseseswswswseswswneswsesenwsese
wnwwwsenewswswswnewswswse
nwnwenwnenenwnwneenenwwwnwnenwswnwe
eeesweseeeeeeeeeeenewnee
swnwnwnwnwneneenenenenwnwnenenenwnenwnw
nenwwnwnwwsenenwnesenwswnwwwwewww
senenwswnewnwnwnewwnwsenwneneneneneenene
swseswseswswswsweswswswswswseswnwswsese
ewneesweneneeswneeneeneneneenwewne
wsewwnwwwnewnwnwswwwnwnewwwww
sewseneswseseeswneesewnweenwsweeese
swswswweswswwswwnwswneswswswswwwswsw
neswswswsewswwswswenwswsw
swswwenesesenwnwswswseenwse
nwnenwnwnwswenwnwnwnenwnwnwnwnwnwsenwnwsw
swenwnenwseeenweeeneneeeeeesw
nwnwnwnwnwsenwnwnwnwnwnwnwwnwwnwsenwnwne
eseeeseenwewseeeeeesenweeese
wwwwnwwwnewwwwwwwwwse
seswnesewwneseseseseseseseswsesesesese
seswswswswswswswswseseswswwneswswseswsw
nwnwenenwnenwnwnwenwnwnwnwnwnwnwnwswswnwnw
sesesesenesenwseseseneswwseswsenesewse
neswneswswswwseswwswswwwsenwswneswsww
nwnwwwnwnwwnwsewenwswnenenwnwswsenw
eseseeseseseeneeseseseseeswsese
nwwwnwenwnwnwwnwnwwnwwnwswwnenwnwnw
nwnwnwnwnwnwnwnwnwnwnwnwenwnwwnwwnwsesw
nwneswneneeeeeneseneeeeeesweene
seeseseseweseseeeseseeeesenwse
swneseswswseseeswswneseswswnwswswsewsw
wwnwnwswnwnwnewewnwwwnwwwwswwnwnw
nenenenewnenenwenenene
seseseswswswseseswseswnwsesesesw
senenesweseseweswswswseswsewneesenww
nwsewnwnwnwnwnwnwnwnwnwnenwnenwnwnwnwnw
seeeneenwesweeeese
wswwswwneswwswwswswwwwwsw
eeeseeeeeneneeeeweswnwneeswnwse
senwnenwnenenenwnwnwnwnenenwwnenenw
wwseswswswewnwwewwwwwwneswsw
eeeswseswseenweenweseeseswnenee
eeeeeeeeseeeeeeweneeese
eewenwneneneneswneneswnwsenenw
wenenenenwnwnwnenwswnenwnenwnwnwnwnenwnw
esesesesesenwsewsesesesesesenesesesese
wwwwweswswswww
weswswswswswswwswswswswswneswwswesw
eseseseseswnesesewseseenwswneswseww
seseesewseneeseseeseeseenewsesee
eeneeswenweeneeneeneeswseweene
eneenwnweeeeseeese
neneneneewneneseneneneeneenenewenene
eewsesweneweswnwnesese
ewwswswneswsenwswneswswswseswswwwsw
wnwsenwnwwnewwnwwseswswwewnwwwe
wswwwwwswswswswneswwswswswswwswe
wnwnwnwwwewwwwnwnwnwnw
nwesesenwwenwnwsewneswnenew
nenenenwswnenenenwnwnenenwneneneenenene
nwseswnwwnwnwwnwwnwnwnwnwnwseenwnwnwne
neneenwswwswnenesenwne
seswwseswwweswneswnenenwswsenwswwsw
nwseswswwswswswswnwseswnwwswseswswswsww
wwnewwwewwwwwwnwnwswwwwww
neneswnenwnenenenenenenwneneswnenwnenene
wwnwnwsesenwnwenwnwnwnwnwewnwnwnww
eneenwneneneneeeeneenesweesweee
swsewswwseseswswswseswseseeswswneswswsesw
swewwwwwwnwwswwwewwwnwnwwww
eeesenesewweseneseswweseeeesee
wnwweseenwwwwwnwwnwnwnesenewswse
nenenenenenesewnenenenenenenene
swseswneswneswsewswsesenwswswseseswswsw
wnwwwnwwenwnwswnwnwwnwwnwnwnwww
sewsenweeeseeseeeeeeeesesesee
enwsweweeeeneneeeeneeneswse
nwnwnewnwwnwwnwnwnwwnwnwnwsenwnwnwnw
swswwnesesewnwswswnwswswsewswswnewsw
swnesenwnwnwnwnenenwnw
neseeseseswwnwsenwswseswswnw
swswswneweswnwswwwwwseswwswsw
neneneswnwneneneneneswnenesenenenwnenwne
swseseeewneeseswseseeseneenweese
eseseeeenwseseeesesesee
wwnwwwwwnwwwwwnwwwswnwweew
newneeeneneeneene
swswwwswweswnwswswswswswswswwseswswsw
nwnwnwnwnwnenwneswnwnwsenwenwnwnwnwwnwnwnw
seswwwwwwwnwswwswneswswwswswswsw
neneenesenenweneesewenenweeswee
seseseseseseseseseseseswesesesesenwswse
neeneneenenenenenenesenesweneneeneenw
nwwswseeseewenwnwwewwnwnenwew
neswneneeneneenwnwnenenenwnwnewnenesw
nwesewnwnwnwnwnwnenwnwnw
nwnwnenwewenwnwnesewseswswnwnwenese
swsweswnwswseswnwswswswsweswswswswsesw
eweeneseeneeeeeeseeesweeee
ewsenwnwnwnwswnwnwswsenwnenwswnwnwnwnenw
enesenewwnwwseseswnwseesenenwseesese
wwwwnenwewwnwwwwwwnwwsewwesw
swwswwwseswnesewnew
neewswwsenwwsenwsewnwwnwnenwnwenw
eneneneesweeneneeneeneneenwneee
swswewswswwwswswswswseeswwswswswnwsw
wnenenewwneneesenesenwwsenwenwwsene
nweeswnwnwnwnwswnwnwenwwnenwsesenewnw
enwwwwnwwwwnwwnwnwwwnwwnweswnw
swnwwswswewwswswswnwwnesewwswswsw
nwenwnwwnenwswnwnwwnwnwnenenwneenwnw
neneneneewneneneseneeeneeesweneeee
swwseswwwswnwswwneneseswswewnewswswnw
swsenwneseenwnwnwswnwwnenwwswnenwwwse
nwnenwnwneneswnwnesenenw
sesweswswwsesesenwsewenweswswsese
ewswsenwsewnwsesweseneswswswwne
swseeenweeseneenwsewnw
nwwwewwwwnwwwnwwwwwwwewnw
newsenwneswnwnenwnwnwneenwnwnenwnwnenw
wwwewnwnwnwwwwwnwwwsenwwwnwnw
eseeseewnenewweneswneneeeneewe
swswnwswseswswswswswweswswswswswswswswsw
neeeseeeneeeeweseenwneeeee
enenwwenwnewswewwnwswwswnwswnew
wwwsesesewwwwwnwnwwnewwwwwwne
wwwwwwswswwwwwnenewswswwww
enweseeeeeeneneweeeeenenee
senenenenwnenenenenenewneeswnenenenenene
wnwwwwwwwwwwwswnewnwwwnw
eswwesenweneneeneenwenenenewswse
nwnwnwswnwnwneneneneswnwnw
sewswneswwsenwswwswseswwsweswnwswswsw
wseeneeneseseeseswsesweeseeeneese
nwnwnwswnwnwwwnwneswnwnwnwwwweswnew
seseseseswnwseseseesesesesesesesw
swswswswswnewswwswswswse
senwseseseseseswneseswseseseswwsesesesesw
wenwnwswnenwnwnwsewnwnwesenwwsenenesw
eneneweneeswneeseeeenee
sesewswnwseswswswsewswswseeeneswswene
nwwwnwwwwseewwwenwwwswnwwwwnw
wwswsewwwsenwwesewnwnwnwwnwnewww
seswseseewseswseseseswse
wnwwwnwwwwwswwwnesesewnewnew
swseswseseswswswswswsenwswsesweseswswnwsw
neeeseseseneseswseseeseseseswesesesee
eswnewneseeneenenene
wneneenweesenewneeeesenenee
neswnenwwswswswswswwnenwswseswseesww
nesenwnenwnwswnwnwswnenwnwnenwnw
nenenwneswnenenenenenenwnwnwnwnenwnwswenw
eeseseeeesenwsenweeeesee
esenesesesenesewseswsesesesesesesewsesene
swneneneneneneenenenenenenwnwneneswneneene
seswseseswseswseseseseswseneswswnwseswnw
eswnewneneneeneneneneeneswneswwnwne
nwnenwnwsenwnwnwsewnwnwnwnwnwnwsewnenwnw
neneneneswneesewwenwnesesenwswnwnwnenenw
neneswneenwnewnenenenenenwnenenenenenene
swwweswswweswwwswwswnwwwswnwswww
wwwwswnwwwwwswswse
swswswneswswswswswnwswswswswswswseswswwsw
newsenweneswenenenewneenwsenwwnewnw
eeseneeeweneenee
swswswswswswswsweswswswnwswnwsweswswsw
nwsenwnwnwwnwnenwnwwnwnwnwwswswnewne
enewsewneneeeenenenenenenenenesenene
newneeeeneneeseeenweeeeswee
seeewswwseswwneneswswswswwwswswesw
seseenesesesesesesewse
nwswnwnenwnwnesenwnwnwnenwnenene
eseseseeeeseenwseseeeswsesesenwesee
swnwseswseswnwseeenwswswswsewswesesw
wwwwnwwwswseeswnwwwwwwsw
wsenwwneewnwsww
senewswenesesesweseseeswseseseenesese
nwseseseeseseswseeseesesesenesesenwsw
nwnenwenenwnwwnenwswnwsenwnenw
seseeeeeneewweweeseneeeese
wseswswswnweswwwnwwwswswswwewswswsw
newenwnwnenwnenenwnwnenenwsenesenwswnwne
sweeeeeeneneeeeeneweswnwswe
swnwswenwnwswnenenwneenwnwnwnwnwnwnwnw
nwnwnwnwnwenwnwswnwswnwnwenwnwnwwnwnesese
eswneseenewsewwewsenesenesewneesese
neseeeeseseswsesewseseseewsesenesese
nenwwnesweeeneneneenenwnesw
wneeneesweneenene
eseeweeseseeeneeeeeeeeee
neenwneeweswnwswnwneneneneswewnwnwnese
nenenwnenwnenenenenewnwnwnwnesenenenwnw
neneeneweneseeeneeeneneeeeene
wseesweeeeseseenweeeseseeee
eswnwnewwnwswswewswsw
wewewneswsenenwenewwwwseswww
eswnwenwnwseseseenwnwwnenwnwweseswnwse
wswswswswseewneseswswwenwwneswnwswsee
swswswswenwsenwswswswswseswseswsesesw
nwswewwseenwswneeee
swnwwwnwewesewwenwwwnwwswww
nwnwswnwwnwnwnwwnwnwnwnwenwnwnwnwnwnw
eweseenweenesesee
wsenwnwseswwswswwnenwnweswnwseeewswnw
neeneneneeesweswnenwneneenenweneese
swswseswswswwwswswnwswswwweswwwnww
eeeseseneeweeeeeseenweeese
wswwwwnwnwnwsenenwwnwenw
nwnwnwnwnenwnwwwnwnwswnwswswnwewwe
ewewwwnwwswseseseseeeseneeseee
swwswwwwwwswewwwwwwwwew
seseseeesweswwenwnw
nwnwsewweswnwww
wwnewwwswwwsewswsw
seswwwwswewswwsewwwwwwnewwnww
wwwswnwswwnewwsewwwwwwswew
nwswswnenenwnenwsene
swswsesenwseswsesesweswswswswseswswsw
wwsweeswwwswwswswwnesw
nwnwnwsesesewnwewnwwnewnwwnwnwnwesw
enwwnwswwsweswneswnwwswnweeswsesw
neeeneseseeeenwneeneeeweweese
nwwsenwwnwwnwnwnwnwnwnwnw
nwnwnenwwswnwswnwnesenwnwwnweneewse
sweneswnesenenenewnenenenenwenwnwnenesenw
nwnenweeswnwsesenwnwnwnwnenwwenew
nweseeeseseseeeseseswneswseeeswsenwse
eneneeeneweneesene
nwnwswnenwnwnwnwnenwnwnenwnwsenenwnwwnwnwnw
swweswnwwswwswswneswwswnenwneswewsw
wswwwnwswwsewseewswswswwwwswne
nwnesenenenwewwneneseneneneewnenenese
neswwswswnwwwwswesweswwswswnewswnw
newenesenenwnenwwneswneseeenenwnene
nweswnwneswsenweeeesesesewenwee
nwsenenenenenenwwnenwnwnenenenenenwneneswne
swswswswswsenwneseswswswwswseswswswne
swneswswswswswseswsewswsw
senwesenwnwnwnwnwwnwwnewnwneswnwnwnw
seswseswswseswswseseswnwswnwswswseseese
nenenenenenenenwnwnenwneswnenenwne
nwnwnenwnenwnenwnenenwnwnenenenwneneesw
nwswnwnewnenwenenwnwnesenwnwnwnenenenenwnw
wswnwnewwwnwswsewwnwwswnesene
nwnenwnwnwenwnenwnewnwsenwswswnwwnwnwwnw
wwnewwswswwsewwwswwwsewwwnwww
sewnwenwnwsenewnw
seseseweswwswenenwswneswwswneswswsese
wseseseswsenwswwwnwwnenenenewswsww
nwnwenwnwwnwwwnwnwnwnwnwnwnwnwsenww
wsenewenenenenwneenwneswseenwswnww
seseseseseseswseseeseswseseseseswnwsesw
neenwneeeneseeneseneneeneneenenewe
eseswseseseseseseseesesesewneswnewsesw
eswneeesweswneeeeneeenwnweeeee
seseseswseswwswswswswswneseswnwseswswswswsw
swwwswnesewwwswswswswswwswswswnesew
ewsenenwswswwsewsesesenwsenwseneene
neneneneneenenweneneswnenenenenenewsene
wwenwseweswnwnwwwswwswwwewnew
eneeeenwweneeeeneeeneeeneswe
eenewnwswesenwneeseweeseseeswse
senwseesweseeswsesesesesenweeseesese
wswwsenenwewnwwnesewnwswwwsewnwnw
swneseswswweenwwwwwewwwswwsw`;
/** */
